-- CreateEnum
CREATE TYPE "StaffPosition" AS ENUM ('LSPD_DETECTIVE_I', 'LSPD_DETECTIVE_II', 'LSPD_DETECTIVE_III', 'LSPD_LIEUTENANT_IN_CHARGE', 'LSSD_DETECTIVE_I', 'LSSD_DETECTIVE_II', 'LSSD_DETECTIVE_III', 'LSSD_LIEUTENANT_IN_CHARGE');

-- AlterTable
ALTER TABLE "AdminUser" ADD COLUMN     "position" "StaffPosition";
